// Generated by Wrangler on Fri Jul 12 2024 14:55:25 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	dogImages: R2Bucket;
	dogsDB: D1Database;
}
