// Generated by Wrangler on Wed Sep 25 2024 08:55:35 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES__KV_SUSPENSE_CACHE: KVNamespace;
	wrappingKey: string;
	dogImages: R2Bucket;
	dogsDB: D1Database;
	dogsDB_live: D1Database;
}
