// Generated by Wrangler on Wed Oct 16 2024 07:43:02 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES__KV_SUSPENSE_CACHE: KVNamespace;
	wrappingKey: string;
	ZOHO_CLIENT_ID: string;
	ZOHO_CLIENT_SECRET: string;
	ZOHO_REFRESH_TOKEN: string;
	dogImages: R2Bucket;
	dogsDB: D1Database;
	dogsDB_live: D1Database;
}
