
DROP TABLE IF EXISTS ClfDogs;
DROP TABLE IF EXISTS HusbandDogs;
DROP TABLE IF EXISTS PastLitters;
DROP TABLE IF EXISTS LitterPhotos;
DROP TABLE IF EXISTS Puppies;


CREATE TABLE ClfDogs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    PAGE TEXT,
    IMAGE_CIRCLE TEXT,
    IMAGE_SQUARE TEXT,
    IS_RETIRED BOOLEAN,
    IS_EXPECTING BOOLEAN,
    HAS_DELIVERED BOOLEAN,
    DUE_DATE TEXT,
    HUSBAND TEXT,
    BIRTHDAY TEXT,
    COLOR TEXT,
    EYE_COLOR TEXT,
    NOSE_COLOR TEXT,
    ENERGY_LEVEL TEXT,
    WEIGHT INTEGER,
    PERSONALITY TEXT,
    FAVORITE_ACTIVITIES TEXT,
    CURRENT_LITTER_GROUP_PHOTO TEXT,
    CURRENT_LITTER_BIRTHDAY TEXT,
    CURRENT_LITTER_GO_HOME_DATE TEXT
);

CREATE TABLE HusbandDogs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    IMG TEXT,
    BREEDER TEXT,
    BIRTHDAY TEXT,
    COLOR TEXT,
    EYE_COLOR TEXT,
    NOSE_COLOR TEXT,
    ENERGY_LEVEL TEXT,
    WEIGHT INTEGER,
    PERSONALITY TEXT,
    FAVORITE_ACTIVITIES TEXT
);

CREATE TABLE PastLitters (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LITTER_ID TEXT,
    MOTHER TEXT,
    FATHER TEXT,
    GROUP_PHOTO TEXT,
    BIRTHDAY TEXT,
    GO_HOME_DATE TEXT
);

CREATE TABLE LitterPhotos (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LITTER_ID TEXT,
    PHOTO_URL TEXT,
    PUPPY_COLORS TEXT
);

CREATE TABLE Puppies (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LITTER_ID TEXT,
    COLOR TEXT,
    IMG TEXT,
    NAME TEXT,
    GO_HOME_OVERRIDE TEXT,
    BIRTHDAY_OVERRIDE TEXT
);


INSERT INTO ClfDogs (NAME, PAGE, IMAGE_CIRCLE, IMAGE_SQUARE, IS_RETIRED, IS_EXPECTING, HAS_DELIVERED, DUE_DATE, HUSBAND, BIRTHDAY, COLOR, EYE_COLOR, NOSE_COLOR, ENERGY_LEVEL, WEIGHT, PERSONALITY, FAVORITE_ACTIVITIES, CURRENT_LITTER_GROUP_PHOTO, CURRENT_LITTER_BIRTHDAY, CURRENT_LITTER_GO_HOME_DATE)
VALUES ('Piper', '<page-url>', '<image-url>', '<image-url>', 0, 0, 1, 'MM-DD', 'Knox', 'YYYY-MM-DD', 'Apricot and Cream', 'Brown', 'Black', 'Medium - Low', 47, 'Sweet, social, confident, cuddly, great on/off switch', 'Piper enjoys cuddling, playing, running, being a dog, etc.', '<image-url>', 'YYYY-MM-DD', 'MM-DD');


INSERT INTO HusbandDogs (NAME, IMG, BREEDER, BIRTHDAY, COLOR, EYE_COLOR, NOSE_COLOR, ENERGY_LEVEL, WEIGHT, PERSONALITY, FAVORITE_ACTIVITIES)
VALUES ('Knox', '<image-url>', 'Gravelle Family Farms', 'YYYY-MM-DD', 'Red and White', 'Amber', 'Brown', 'Low', 33, 'Gentle, affectionate, social, confident', 'Knox likes cuddling, playing, running, being a dog, etc.');


INSERT INTO PastLitters (LITTER_ID, MOTHER, FATHER, GROUP_PHOTO, BIRTHDAY, GO_HOME_DATE)
VALUES ('PIPER-1', 'Piper', 'Knox', '<image-url>', 'YYYY-MM-DD', 'MM-DD');


INSERT INTO LitterPhotos (LITTER_ID, PHOTO_URL, PUPPY_COLORS)
VALUES ('PIPER-1', '<image-url>', 'RED, GREEN, PURPLE'),
       ('PIPER-1', '<image-url2>', 'YELLOW, BLUE, ORANGE, VIOLET');


INSERT INTO Puppies (LITTER_ID, COLOR, IMG, NAME, GO_HOME_OVERRIDE, BIRTHDAY_OVERRIDE)
VALUES ('PIPER-1', 'RED', '<image-url>', NULL, NULL, NULL);
