#!/usr/bin/env bash

keyfile="./keys.json",

function kv-get {
  yes | npx wrangler kv key list --binding __NEXT_ON_PAGES__KV_SUSPENSE_CACHE  | jq '.[] | .name' | jq -s > $keyfile
}

function kv-clear {
  npx wrangler kv bulk delete $keyfile --binding __NEXT_ON_PAGES__KV_SUSPENSE_CACHE
}


kv-get;
cat $keyfile;
kv-clear;
rm $keyfile;
