// Generated by Wrangler on Sat Jun 22 2024 18:48:13 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	dogsDB: D1Database;
}
