// Generated by Wrangler on Wed Jun 19 2024 13:32:08 GMT-0700 (Pacific Daylight Time)
// by running `wrangler -e preview types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	dogsDB: D1Database;
}
