name: Test Cherry Lane Farms

on:
  push:
    branches: [ preview/test ]

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_PAGES_PROJECT: ${{ secrets.CLOUDFLARE_PAGES_PROJECT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      - name: Install Ubuntu Dependencies
        run: |
          RELEASE=$( lsb_release -rs | cut -d '.' -f1 )
          sudo apt-get update
          # Disable man-db updates which take forever and are unnecessary.
          if [ "$RELEASE" -gt 23 ];
            then
            sudo rm /var/lib/man-db/auto-update
            sudo apt-get install -y libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
            else
            sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          fi

      - name: Clean Install the Project
        run: npm ci

      - name: Deploy project
        run: npm run deploy

      - name: Run Cypress tests on preview URL
        run: |
          npx cypress run \
          --config \
          baseUrl="https://preview-test.${{ secrets.CLOUDFLARE_PAGES_PROJECT }}.pages.dev"

      - name: Get Deployment ID
        run: |
          printf "#################################### CURLING ####################################\n"
          RESPONSE=$(curl "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PAGES_PROJECT }}/deployments?env=preview" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}")
          printf "#################################################################################\n\n"
          printf "############### RESPONSE ###############\n"
          echo "$RESPONSE" | jq -r ".result[0]"
          printf "########################################\n\n"
          DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.result[0].id')
          PREVIEW_URL=$(echo "$RESPONSE" | jq -r '.result[0].url')
          TRIGGER_BRANCH=$(echo "$RESPONSE" | jq -r '.result[0].deployment_trigger.metadata.branch')

          # Handle empty deployments
          if [ "$DEPLOYMENT_ID" == "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
            printf "\e[91m::FAILED::\e[0m: No deployments found.\n\n"
            exit 1
          fi
          echo "Preview URL: $PREVIEW_URL"
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "Trigger Branch: $TRIGGER_BRANCH"

          # Delete the specified Deployment With ID $DEPLOYMENT_ID
          DELRESPONSE=$(curl "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PAGES_PROJECT }}/deployments/$DEPLOYMENT_ID?force=true"  \
            -X DELETE \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}")

          echo "$DELRESPONSE" | jq
